# docker run --name webserver -p 5000:5000 -p 5001:5001  minitwit
FROM golang:latest

RUN go get github.com/prometheus/client_golang/prometheus
RUN go get github.com/prometheus/client_golang/prometheus/promauto
RUN go get github.com/prometheus/client_golang/prometheus/promhttp



WORKDIR /src

COPY . .

EXPOSE 9090

RUN go build /src/metric.go

CMD ["/src/metric"]