version: '3.5'

networks:
  main:

services:

  minitwitimage:
    image: minitwitlocal
    container_name: minitwit
    networks:
      - main
    ports:
        - '5000:5000'
        - '5001:5001'

