
version: '3.5'

networks:
  main:

services:

  minitwitimage:
    image: ${DOCKERHUB_USERNAME}/minitwitimage
    container_name: minitwit
    networks:
      - main
    ports:
        - '5000:5000'
        - '5001:5001'
    depends_on:
        - grafana
        - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - main


  grafana:
    image: grafana/grafana:4.5.2
    ports:
      - "3000:3000"  
    networks:
      - main
