host: localhost:5001
info:
  contact:
    email: dallasmaxwell@outlook.com
    name: API Support
  description: Swagger API for Golang Project MiniTwit.
  license:
    name: Apache 2.0
  termsOfService: http://swagger.io/terms/
  title: MiniTwit Swagger API
  version: "1.0"
paths:
  /latest:
    get:
      produces:
      - application/json
      responses:
        "200": {}
      summary: Get latest accepted id
  /register:
    post:
      parameters:
      - description: User Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: Post new user to register
swagger: "2.0"
