name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag motosh/minitwitimage:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push motosh/minitwitimage:${{steps.vars.outputs.tag}}
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag motosh/minitwitimage:latest
    - name: Push the latest Docker image
      run: docker push motosh/minitwitimage:latest
    - name: Executing remote  command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: cd /vagrant
        

